### NumPy Tutorial

In [3]:
import numpy as np

### The Basics

In [3]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [7]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [10]:
# Get Dimension
b.ndim

2

In [11]:
# Get Shape
b.shape

(2, 3)

In [18]:
# Get data type of element stored in numpy array
a.dtype

dtype('int32')

In [16]:
# Get size of each element in bytes
a.itemsize

4

In [19]:
# Get total size of the whole numpy array
a.nbytes

12

In [20]:
# Get number of elements
a.size

3

### Accessing/Changing specific elements, rows, columns, etc

In [54]:
# 2 by 7 array
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [25]:
# Get a specific element [r, c]
a[1, -2]  # Negative index means counting from the end

np.int64(13)

In [26]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [27]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [29]:
# Getting a little more fancy [row, startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [30]:
# Changing elements
a[1,5] = 20

# Changing a whole column
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


### 3D Example

In [34]:
# Look at it like you are slicing a 3D array vertically
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)
# Face 1 is the first 2D array, face 2 is the second 2D array

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [35]:
# Get specific element (Start from the outermost array) [face, row, column]
b[0,1,1]

np.int64(4)

In [37]:
# Replace 
b[:,1,:] = [[9,9],[8,8]]  # LHS = All faces, 2nd row, All columns

In [39]:
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


### Initializing Different Types of Arrays

In [50]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [51]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [52]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [56]:
# Any other number (full_like)
np.full_like(a, 4)  # Same shape as a, filled with 4
# Can also use np.full(a.shape, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [58]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.56040635, 0.87620036],
       [0.28752339, 0.6248615 ],
       [0.52935355, 0.7715641 ],
       [0.41389959, 0.87567234]])

In [61]:
# Random Integer values (start, end, size)
np.random.randint(-4,8, size=(3,3)) # -4 to 7

array([[ 2,  5,  0],
       [ 6, -1,  4],
       [ 1,  4,  7]], dtype=int32)

In [63]:
# The identity matrix
np.identity(5)  # By nature, identity matrix is always square

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [69]:
# Repeat an array, axis=0 means repeat vertically, axis=1 means repeat horizontally
arr = np.array([[1,2,3],[4,5,6]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]
 [4 5 6]]


In [70]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Be careful when copying arrays!!!

In [72]:
a = np.array([1,2,3])
b = a.copy() # b = a will not work, it will just point to the same memory location
b[0] = 100 # Without copy, a will also change

print(a)

[1 2 3]


### Mathematics

In [79]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [74]:
a + 2

array([3, 4, 5, 6])

In [75]:
a - 2

array([-1,  0,  1,  2])

In [76]:
a * 2

array([2, 4, 6, 8])

In [77]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [80]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [81]:
a ** 2

array([ 1,  4,  9, 16])

In [83]:
# Take the sin
np.sin(a)

# Take the cos
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [84]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

#### Linear Algebra

In [86]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b) # Matrix multiplication

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [88]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)

In [89]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

##### Statistics

In [5]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
np.min(stats)

np.int64(1)

In [7]:
# Axis 0 is vertical, axis 1 is horizontal
np.max(stats, axis=1) # Max of each row

array([3, 6])

In [10]:
# Sum of all elements
np.sum(stats, axis=0) # Sum of each column

array([5, 7, 9])

### Reorganizing Arrays

In [14]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2)) # Must have the same number of elements
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [18]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2]) # I think its better than using the repeat function

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2,h1))

array([[1., 1., 1., 1., 0., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0., 0., 1., 1., 1., 1.]])

### Miscellaneous
##### Load Data from File

In [24]:
# Load data from file
filedata = np.genfromtxt('data.txt', dtype='int32', delimiter=',') # Default dtype is float
# filedata = filedata.astype('int32') -> Change dtype to int32 if dtype is excluded from the first line 
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


#### Boolean Masking and Advanced Indexing

In [32]:
~((filedata > 50) & (filedata < 100)) # ~ is the NOT operator

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [ ]:
## Index with a list in numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]] # Get elements at index 1, 2, 8

## 2D array [row, column]
b = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
b[[0,1,2],[1,2,3]] # Get elements at (0,1), (1,2), (2,3)

array([ 2,  8, 14])